# Generated by Django 3.1.2 on 2020-10-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutcalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
